simulation:
  gui: true
  max_steps: 500
  n_cars_generated: 100
  yellow_duration: 5

agent:
  num_states: 10
  num_actions: 4

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/westTuyenSonBridge/osm.sumocfg"
  model_to_test: "models/2025-05-20_12-00-00_model.h5"

traffic_lights:
  - traffic_light_1:
    id: "cluster_3070397256_6164917307_6164917332_6164917334_#7more"
    detectors:
      - id: "e3_0"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
      - id: "e3_1"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_2"
        lane_idx:
          - 15
          - 16
          - 17
          - 18
          - 19
      - id: "e3_4"
        lane_idx:
          - 10
          - 11
          - 12
          - 13
          - 14
  - traffic_light_2:
    id: "cluster_1333258669_1333279736_6518778049_6518778050"
    detectors:
      - id: "e3_3"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      - id: "e3_5"
        lane_idx:
          - 6
          - 7
          - 8
          - 9
      - id: "e3_6"
        lane_idx:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
      - id: "e3_8"
        lane_idx:
          - 16
          - 17
          - 18
          - 19
  - traffic_light_3:
    id: "cluster_1333246087_3070300095_3078041918_6518727272_#2more"
    detectors:
      - id: "e3_7"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      - id: "e3_11"
        lane_idx:
          - 6
          - 7
          - 8
          - 9
          - 10
      - id: "e3_10"
        lane_idx:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
      - id: "e3_9"
        lane_idx:
          - 17
          - 18
          - 19
          - 20
          - 21