simulation:
  gui: true
  max_steps: 500
  n_cars_generated: 100
  yellow_duration: 5

agent:
  num_states: 10
  num_actions: 4

dir:
  models_path_name: "models/"
  sumocfg_file_name: "intersections/westDragonBridge/osm.sumocfg"
  model_to_test: "models/2025-05-20_12-00-00_model.h5"

intersections:
  - intersection_1:
    id: "clusterJ35_cluster2988146972_9662761813_J33_J34_#1more"
    detectors:
      - id: "e3_0"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_1"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
      - id: "e3_3"
        lane_idx:
          - 11
          - 12
          - 13
          - 14
          - 15
  - intersection_2:
    id: "cluster_2988146960_2988146981_3068684710_6528582411"
    detectors:
      - id: "e3_4"
        lane_idx:
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
      - id: "e3_5"
        lane_idx:
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
      - id: "e3_2"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
  - intersection_3:
    id: "cluster_2988146980_3068684702_6528628239_6528628242_#1more"
    detectors:
      - id: "e3_6"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
      - id: "e3_7"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_8"
        lane_idx:
          - 10
          - 11
          - 12
          - 13