simulation:
  gui: true
  max_steps: 500
  yellow_duration: 5

green_duration_agent:
  num_states: 1
  num_actions: 6

selector_phase_agent:
  num_states: 5
  num_actions: 1

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/westDragonBridge/osm.sumocfg"
  model_to_test: "models/2025-05-20_12-00-00_model.h5"

traffic_lights:
  - traffic_light_1:
    id: "clusterJ35_cluster2988146972_9662761813_J33_J34_#1more"
    detectors:
      - id: "e2_3"
        street: "NVL-DB"
        lane_idx:
          - 15
      - id: "e2_4"
        street: "NVL-DB"
        lane_idx:
          - 14
      - id: "e2_5"
        street: "NVL-DB"
        lane_idx:
          - 13
      - id: "e2_6"
        street: "NVL-DB"
        lane_idx:
          - 12
      - id: "e2_7"
        street: "NVL-DB"
        lane_idx:
          - 11
      - id: "e2_8"
        street: "2/9-DB"
        lane_idx:
          - 10
      - id: "e2_9"
        street: "2/9-DB"
        lane_idx:
          - 9
          - 8
      - id: "e2_10"
        street: "2/9-DB"
        lane_idx:
          - 7
      - id: "e2_11"
        street: "2/9-DB"
        lane_idx:
          - 6
          - 5
      - id: "e2_12"
        street: "DB-NVL"
        lane_idx:
          - 0
          - 1
      - id: "e2_13"
        street: "DB-NVL"
        lane_idx:
          - 2
      - id: "e2_14"
        street: "DB-NVL"
        lane_idx:
          - 3
          - 4
  - traffic_light_2:
    id: "cluster_2988146960_2988146981_3068684710_6528582411"
    detectors:
      - id: "e2_0"
        street: "NVL-DB"
        lane_idx:
          - 20
          - 19
          - 18
      - id: "e2_1"
        street: "NVL-DB"
        lane_idx:
          - 17
      - id: "e2_2"
        street: "NVL-DB"
        lane_idx:
          - 14
          - 15
          - 16
      - id: "e2_15"
        street: "TP-TNV"
        lane_idx:
          - 0
      - id: "e2_16"
        street: "TP-TNV"
        lane_idx:
          - 1
      - id: "e2_17"
        street: "TP-TNV"
        lane_idx:
          - 2
      - id: "e2_18"
        street: "TP-TNV"
        lane_idx:
          - 3
      - id: "e2_19"
        street: "TP-TNV"
        lane_idx:
          - 4
          - 5
          - 6
      - id: "e2_20"
        street: "DB-NVL"
        lane_idx:
          - 7
          - 8
      - id: "e2_21"
        street: "DB-NVL"
        lane_idx:
          - 9
      - id: "e2_22"
        street: "DB-NVL"
        lane_idx:
          - 10
      - id: "e2_23"
        street: "DB-NVL"
        lane_idx:
          - 11
          - 12
          - 13
  - traffic_light_3:
    id: "cluster_2988146980_3068684702_6528628239_6528628242_#1more"
    detectors:
      - id: "e2_24"
        street: "NVL-DB"
        lane_idx:
          - 13
      - id: "e2_25"
        street: "NVL-DB"
        lane_idx:
          - 12
      - id: "e2_26"
        street: "NVL-DB"
        lane_idx:
          - 10
          - 11
      - id: "e2_27"
        street: "PCT-PCT"
        lane_idx:
          - 0
          - 1
      - id: "e2_28"
        street: "PCT-PCT"
        lane_idx:
          - 2
          - 3
          - 4
      - id: "e2_29"
        street: "DB-NVL"
        lane_idx:
          - 5
      - id: "e2_30"
        street: "DB-NVL"
        lane_idx:
          - 7
          - 8
          - 9
      - id: "e2_31"
        street: "DB-NVL"
        lane_idx:
          - 6