simulation:
  gui: False
  total_episodes: 1000
  max_steps: 3600
  interphase_duration: 3

memory:
  memory_size_min: 10
  memory_size_max: 10000

model:
  training_epochs: 1000
  save_model_name: "dqn_testngatu_model"  # Name for saving the model
  load_model_name: null  # Set to model name to load existing model, null to start fresh
  load_q_table_name: null  # Set to Q-table filename to load existing Q-table, null to start fresh
  save_interval: 10  # Save model every N episodes

agent:
  rbf_components: 100   
  rbf_gamma: 0.5 
  gamma: 0.99
  num_states: 4 # min_free_capacity, density, waiting_time, queue_length
  model:
    num_layers: 16
    batch_size: 256
    learning_rate: 0.0001
    decay_rate: 0.995
    min_epsilon: 0.01
    loss_type:
      - qr
  weight:
    queue_length: -0.25
    outflow_rate: 1
    delay: -0.25
    travel_time: 1
    waiting_time: -0.25
    switch_phase: -5

vehicle_counts:
  low:
    motorcycle: 1500
    passenger: 375
    bicycle: 75
    truck: 50
    pedestrian: 100
  medium:
    motorcycle: 3000
    passenger: 750
    truck: 150
    bicycle: 100
    pedestrian: 200
  high:
    motorcycle: 6000
    passenger: 1500
    truck: 300
    bicycle: 200
    pedestrian: 400

edge_groups:
  W:
    - E17
    - E11
    - E10
    - E16 
  S: 
    - E12
    - E13
    - E19
    - E14
  E: 
    - E15
    - E8
    - E9
    - E18
  N: 
    - E22
    - E20
    - E23
    - E21

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/testmodel4/osm.sumocfg"

traffic_lights:
  - traffic_light_1:
    id: "Ngatu"
    phase: 
      - GGGGGrrrGrrrGrrr
      - GrrrGGGGGrrrGrrr
      - GrrrGrrrGGGGGrrr
      - GrrrGrrrGrrrGGGG

    detectors:
      - id: "e2_0"
        street: "1"
      - id: "e2_1"
        street: "1"
      - id: "e2_4"
        street: "2"
      - id: "e2_5"
        street: "2"
      - id: "e2_10"
        street: "3"
      - id: "e2_11"
        street: "3"
      - id: "e2_14"
        street: "4"
      - id: "e2_15"
        street: "4"
  # - traffic_light_2:
  #   id: "NgatuNorth"
  #   phase: 
  #     - GrrrrGGGGGGrGrrGrGrr
  #     - GGGGGGrGrrGrGrrGrrrr
  #     - GrGrrGrGrrGrrrrGGGGG
  #     - GrGrrGrrrrGGGGGGrGrr

  #   detectors:
  #     - id: "e2_20"
  #       street: "1"
  #     - id: "e2_21"
  #       street: "1"
  #     - id: "e2_18"
  #       street: "2"
  #     - id: "e2_19"
  #       street: "2"
  #     - id: "e2_16"
  #       street: "3"
  #     - id: "e2_17"
  #       street: "3"
  #     - id: "e2_22"
  #       street: "4"
  #     - id: "e2_23"
  #       street: "4"
  # - traffic_light_3:
  #   id: "NgatuSouth"
  #   phase: 
  #     - GrrrrGGGGGGrGrrGrGrr
  #     - GGGGGGrGrrGrGrrGrrrr
  #     - GrGrrGrGrrGrrrrGGGGG
  #     - GrGrrGrrrrGGGGGGrGrr

  #   detectors:
  #     - id: "e2_2"
  #       street: "1"
  #     - id: "e2_3"
  #       street: "1"
  #     - id: "e2_6"
  #       street: "2"
  #     - id: "e2_7"
  #       street: "2"
  #     - id: "e2_8"
  #       street: "3"
  #     - id: "e2_9"
  #       street: "3"
  #     - id: "e2_12"
  #       street: "4"
  #     - id: "e2_13"
  #       street: "4"

accident:
  start_step: 400
  duration: 100
  junction:
    - id: "Ngatu"
