simulation:
  gui: true
  total_episodes: 1000
  max_steps: 500
  interphase_duration: 5

memory:
  memory_size_min: 1000
  memory_size_max: 10000

model:
  training_epochs: 1000

green_duration_agent:
  num_states: 1
  num_actions: 6
  gamma: 0.99
  model:
    num_layers: 3
    batch_size: 64
    learning_rate: 0.0001
    actions_space:
      - -3
      - -2
      - -1
      - 0
      - 1
      - 2
      - 3

selector_phase_agent:
  num_states: 5
  num_actions: 1
  gamma: 0.99
  model:
    num_layers: 3
    batch_size: 64
    learning_rate: 0.0001

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/westDragonBridge/osm.sumocfg"

traffic_lights:
  - traffic_light_1:
    id: "clusterJ35_cluster2988146972_9662761813_J33_J34_#1more"
    detectors:
      - id: "e3_0"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_1"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
      - id: "e3_3"
        lane_idx:
          - 11
          - 12
          - 13
          - 14
          - 15
  - traffic_light_2:
    id: "cluster_2988146960_2988146981_3068684710_6528582411"
    detectors:
      - id: "e3_4"
        lane_idx:
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
      - id: "e3_5"
        lane_idx:
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
      - id: "e3_2"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
  - traffic_light_3:
    id: "cluster_2988146980_3068684702_6528628239_6528628242_#1more"
    detectors:
      - id: "e3_6"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
      - id: "e3_7"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_8"
        lane_idx:
          - 10
          - 11
          - 12
          - 13