simulation:
  gui: true
  total_episodes: 1000
  max_steps: 500
  n_cars_generated: 100
  green_duration: 30
  yellow_duration: 5

model:
  num_layers: 3
  width_layers: 128
  batch_size: 64
  learning_rate: 0.0001
  training_epochs: 10

memory:
  memory_size_min: 1000
  memory_size_max: 10000

agent:
  num_states: 10
  num_actions: 4
  gamma: 0.99

dir:
  models_path_name: "models/"
  sumocfg_file_name: "intersections/westTuyenSonBridge/osm.sumocfg"

intersections:
  - intersection_1:
    id: "cluster_3070397256_6164917307_6164917332_6164917334_#7more"
    detectors:
      - id: "e3_0"
        lane_idx:
          - 5
          - 6
          - 7
          - 8
          - 9
      - id: "e3_1"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
      - id: "e3_2"
        lane_idx:
          - 15
          - 16
          - 17
          - 18
          - 19
      - id: "e3_4"
        lane_idx:
          - 10
          - 11
          - 12
          - 13
          - 14
  - intersection_2:
    id: "cluster_1333258669_1333279736_6518778049_6518778050"
    detectors:
      - id: "e3_3"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      - id: "e3_5"
        lane_idx:
          - 6
          - 7
          - 8
          - 9
      - id: "e3_6"
        lane_idx:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
      - id: "e3_8"
        lane_idx:
          - 16
          - 17
          - 18
          - 19
  - intersection_3:
    id: "cluster_1333246087_3070300095_3078041918_6518727272_#2more"
    detectors:
      - id: "e3_7"
        lane_idx:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      - id: "e3_11"
        lane_idx:
          - 6
          - 7
          - 8
          - 9
          - 10
      - id: "e3_10"
        lane_idx:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
      - id: "e3_9"
        lane_idx:
          - 17
          - 18
          - 19
          - 20
          - 21