simulation:
  gui: True
  total_episodes: 1000
  max_steps: 3600
  interphase_duration: 5

memory:
  memory_size_min: 10
  memory_size_max: 10000

model:
  training_epochs: 1000

agent:
  gamma: 0.99
  num_states: 6 # min_free_capacity, density, waiting_time, queue_length, desra_phase_id, desra_green_time
  green_duration_deltas: [-2, -1, 0, 1, 2] 
  model:
    num_layers: 8
    batch_size: 128
    learning_rate: 0.0001
    decay_rate: 0.995
    min_epsilon: 0.01
  weight:
    green_time: 0.1
    outflow_rate: 0.3
    travel_speed: 0.2
    travel_time: 0.2
    density: 0.2

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/testmodel/osm.sumocfg"

traffic_lights:
  - traffic_light_1:
    id: "Ngatu"
    phase: 
      - GGGGGrrrrrrrrrrrGGGGGrrrrrrrrrrr
      - GrrrrrrrGrrrrGGGGrrrrrrrGrrrrGGG
      - GrrrrGGGGrrrrrrrGrrrrGGGGrrrrrrr
      - rrrrrrrrGGGGGrrrrrrrrrrrGGGGGrrr

    detectors:
      - id: "e2_0"
      - id: "e2_1"
      - id: "e2_2"
      - id: "e2_3"
      - id: "e2_4"
      - id: "e2_5"
      - id: "e2_6"
      - id: "e2_7"
      - id: "e2_8"
      - id: "e2_9"
      - id: "e2_10"
      - id: "e2_11"   
      - id: "e2_12"
      - id: "e2_13"
      - id: "e2_14"
      - id: "e2_15"

accident:
  start_step: 400
  duration: 100
  junction:
    - id: "Ngatu"
