simulation:
  gui: true
  total_episodes: 1000
  max_steps: 500
  green_duration: 30
  yellow_duration: 5

model:
  num_layers: 3
  width_layers: 128
  batch_size: 64
  learning_rate: 0.0001
  training_epochs: 10

memory:
  memory_size_min: 1000
  memory_size_max: 10000

model:
  training_epochs: 1000

green_duration_agent:
  num_states: 1
  num_actions: 6
  gamma: 0.99
  model:
    num_layers: 3
    batch_size: 64
    learning_rate: 0.0001
    actions_space:
      - -3
      - -2
      - -1
      - 0
      - 1
      - 2
      - 3

selector_phase_agent:
  num_states: 5
  num_actions: 1
  gamma: 0.99
  model:
    num_layers: 3
    batch_size: 64
    learning_rate: 0.0001

dir:
  models_path_name: "models/"
  sumocfg_file_name: "simulations/westTuyenSonBridge/osm.sumocfg"

traffic_lights:
  - traffic_light:
    id: "cluster_3070397256_6164917307_6164917332_6164917334_#7more"
    detectors:
      - id: "e2_0"
        lane_idx:
          - 0
      - id: "e2_1"
        lane_idx:
          - 1
      - id: "e2_2"
        lane_idx:
          - 2
          - 3
          - 4
      - id: "e2_3"
        lane_idx:
          - 7
          - 8
          - 9
      - id: "e2_4"
        lane_idx:
          - 6
      - id: "e2_5"
        lane_idx:
          - 5
      - id: "e2_6"
        lane_idx:
          - 12
          - 13
          - 14
      - id: "e2_7"
        lane_idx:
          - 11
      - id: "e2_8"
        lane_idx:
          - 10
      - id: "e2_9"
        lane_idx:
          - 15
      - id: "e2_10"
        lane_idx:
          - 16
      - id: "e2_11"
        lane_idx:
          - 17
          - 18
          - 19
  - traffic_light:
    id: "cluster_1333258669_1333279736_6518778049_6518778050"
    detectors:
      - id: "e2_12"
        lane_idx:
          - 0
          - 1
      - id: "e2_13"
        lane_idx:
          - 2
      - id: "e2_14"
        lane_idx:
          - 3
          - 4
          - 5
      - id: "e2_15"
        lane_idx:
          - 6
          - 7
          - 8
          - 9
      - id: "e2_16"
        lane_idx:
          - 16
          - 17
          - 18
          - 19
      - id: "e2_17"
        lane_idx:
          - 13
          - 14
          - 15
      - id: "e2_18"
        lane_idx:
          - 12
      - id: "e2_19"
        lane_idx:
          - 10
          - 11
  - traffic_light:
    id: "cluster_1333246087_3070300095_3078041918_6518727272_#2more"
    detectors:
      - id: "e2_20"
        lane_idx:
          - 0
          - 1
      - id: "e2_21"
        lane_idx:
          - 2
      - id: "e2_22"
        lane_idx:
          - 3
          - 4
          - 5
      - id: "e2_23"
        lane_idx:
          - 17
          - 18
      - id: "e2_24"
        lane_idx:
          - 19
          - 20
          - 21
      - id: "e2_25"
        lane_idx:
          - 8
          - 9
          - 10
      - id: "e2_26"
        lane_idx:
          - 6
          - 7
      - id: "e2_27"
        lane_idx:
          - 14
          - 15
          - 16
      - id: "e2_28"
        lane_idx:
          - 13
      - id: "e2_29"
        lane_idx:
          - 11
          - 12